# Generated by Django 4.0.8 on 2022-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netoshardwareinventory',
            name='product_raw_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
