# Generated by Django 4.0.8 on 2022-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0006_alter_netoshardwareeol_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netoshardwareeol',
            name='announcement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
