# Generated by Django 4.0.8 on 2022-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0007_alter_netoshardwareeol_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netossoftwareeol',
            name='data',
        ),
        migrations.RemoveField(
            model_name='netossoftwareeol',
            name='name',
        ),
        migrations.RemoveField(
            model_name='netossoftwareeol',
            name='slug',
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='announcement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='bulletin',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='bulletin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='end_of_routine_failure_analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='end_of_service_contract_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='last_day_for_service_contract',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='last_day_of_support_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='last_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_option',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_product_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='migration_strategy',
            field=models.CharField(blank=True, max_length=1334, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='product_id',
            field=models.CharField(default=1, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='product_id_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='product_migration_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='record_update_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netossoftwareeol',
            name='vulnerability_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
