# Generated by Django 4.0.8 on 2022-12-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0008_remove_netossoftwareeol_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netossoftwareeol',
            name='software_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_eol', to='netos.netossoftwareinventory'),
        ),
    ]
